// Code generated by Thrift Compiler (0.20.0). DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"line"
)

var _ = line.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  SendMessageResponse sendMessage()")
  fmt.Fprintln(os.Stderr, "  UnsendMessageResponse unsendSquareMessage()")
  fmt.Fprintln(os.Stderr, "  FetchMyEventsResponse fetchMyEvents()")
  fmt.Fprintln(os.Stderr, "  GetSquareEmidResponse getSquareEmid()")
  fmt.Fprintln(os.Stderr, "  GetSquareMembersBySquareResponse getSquareMembersBySquare()")
  fmt.Fprintln(os.Stderr, "  ManualRepairResponse manualRepair()")
  fmt.Fprintln(os.Stderr, "  InviteIntoSquareChatResponse inviteIntoSquareChat()")
  fmt.Fprintln(os.Stderr, "  InviteToSquareResponse inviteToSquare()")
  fmt.Fprintln(os.Stderr, "  GetJoinedSquaresResponse getJoinedSquares()")
  fmt.Fprintln(os.Stderr, "  MarkAsReadResponse markAsRead()")
  fmt.Fprintln(os.Stderr, "  ReactToMessageResponse reactToMessage()")
  fmt.Fprintln(os.Stderr, "  FindSquareByInvitationTicketResponse findSquareByInvitationTicket()")
  fmt.Fprintln(os.Stderr, "  FetchSquareChatEventsResponse fetchSquareChatEvents()")
  fmt.Fprintln(os.Stderr, "  GetSquareResponse getSquare()")
  fmt.Fprintln(os.Stderr, "  GetJoinableSquareChatsResponse getJoinableSquareChats()")
  fmt.Fprintln(os.Stderr, "  CreateSquareResponse createSquare()")
  fmt.Fprintln(os.Stderr, "  GetSquareChatAnnouncementsResponse getSquareChatAnnouncements()")
  fmt.Fprintln(os.Stderr, "  GetSquareFeatureSetResponse getSquareFeatureSet()")
  fmt.Fprintln(os.Stderr, "  GetSquareChatFeatureSetResponse getSquareChatFeatureSet()")
  fmt.Fprintln(os.Stderr, "  GetJoinedSquareChatThreadsResponse getJoinedSquareChatThreads()")
  fmt.Fprintln(os.Stderr, "  CreateSquareChatThreadResponse createSquareChatThread()")
  fmt.Fprintln(os.Stderr, "  GetSquareChatThreadResponse getSquareChatThread()")
  fmt.Fprintln(os.Stderr, "  JoinSquareChatThreadResponse joinSquareChatThread()")
  fmt.Fprintln(os.Stderr, "  SyncSquareMembersResponse syncSquareMembers()")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
  var m map[string]string = h
  return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
  parts := strings.Split(value, ": ")
  if len(parts) != 2 {
    return fmt.Errorf("header should be of format 'Key: Value'")
  }
  h[parts[0]] = parts[1]
  return nil
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  headers := make(httpHeaders)
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  var cfg *thrift.TConfiguration = nil
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
    if len(headers) > 0 {
      httptrans := trans.(*thrift.THttpClient)
      for key, value := range headers {
        httptrans.SetHeader(key, value)
      }
    }
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans = thrift.NewTSocketConf(net.JoinHostPort(host, portStr), cfg)
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransportConf(trans, cfg)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactoryConf(cfg)
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactoryConf(cfg)
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryConf(cfg)
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := line.NewSquareServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "sendMessage":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "SendMessage requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.SendMessage(context.Background()))
    fmt.Print("\n")
    break
  case "unsendSquareMessage":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "UnsendSquareMessage requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.UnsendSquareMessage(context.Background()))
    fmt.Print("\n")
    break
  case "fetchMyEvents":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "FetchMyEvents requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.FetchMyEvents(context.Background()))
    fmt.Print("\n")
    break
  case "getSquareEmid":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetSquareEmid requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetSquareEmid(context.Background()))
    fmt.Print("\n")
    break
  case "getSquareMembersBySquare":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetSquareMembersBySquare requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetSquareMembersBySquare(context.Background()))
    fmt.Print("\n")
    break
  case "manualRepair":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "ManualRepair requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.ManualRepair(context.Background()))
    fmt.Print("\n")
    break
  case "inviteIntoSquareChat":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "InviteIntoSquareChat requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.InviteIntoSquareChat(context.Background()))
    fmt.Print("\n")
    break
  case "inviteToSquare":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "InviteToSquare requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.InviteToSquare(context.Background()))
    fmt.Print("\n")
    break
  case "getJoinedSquares":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetJoinedSquares requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetJoinedSquares(context.Background()))
    fmt.Print("\n")
    break
  case "markAsRead":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "MarkAsRead requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.MarkAsRead(context.Background()))
    fmt.Print("\n")
    break
  case "reactToMessage":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "ReactToMessage requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.ReactToMessage(context.Background()))
    fmt.Print("\n")
    break
  case "findSquareByInvitationTicket":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "FindSquareByInvitationTicket requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.FindSquareByInvitationTicket(context.Background()))
    fmt.Print("\n")
    break
  case "fetchSquareChatEvents":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "FetchSquareChatEvents requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.FetchSquareChatEvents(context.Background()))
    fmt.Print("\n")
    break
  case "getSquare":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetSquare requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetSquare(context.Background()))
    fmt.Print("\n")
    break
  case "getJoinableSquareChats":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetJoinableSquareChats requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetJoinableSquareChats(context.Background()))
    fmt.Print("\n")
    break
  case "createSquare":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "CreateSquare requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.CreateSquare(context.Background()))
    fmt.Print("\n")
    break
  case "getSquareChatAnnouncements":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetSquareChatAnnouncements requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetSquareChatAnnouncements(context.Background()))
    fmt.Print("\n")
    break
  case "getSquareFeatureSet":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetSquareFeatureSet requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetSquareFeatureSet(context.Background()))
    fmt.Print("\n")
    break
  case "getSquareChatFeatureSet":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetSquareChatFeatureSet requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetSquareChatFeatureSet(context.Background()))
    fmt.Print("\n")
    break
  case "getJoinedSquareChatThreads":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetJoinedSquareChatThreads requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetJoinedSquareChatThreads(context.Background()))
    fmt.Print("\n")
    break
  case "createSquareChatThread":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "CreateSquareChatThread requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.CreateSquareChatThread(context.Background()))
    fmt.Print("\n")
    break
  case "getSquareChatThread":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetSquareChatThread requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetSquareChatThread(context.Background()))
    fmt.Print("\n")
    break
  case "joinSquareChatThread":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "JoinSquareChatThread requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.JoinSquareChatThread(context.Background()))
    fmt.Print("\n")
    break
  case "syncSquareMembers":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "SyncSquareMembers requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.SyncSquareMembers(context.Background()))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
